name: JustHorse
version: 2.4-LEGACY
main: su.spyme.justhorse.Main
description: Horse plugin for Hub server (for 1.12.2)
author: SPY_me
commands:
  justhorse:
    aliases: [horse]
    description: Summon personal horse